version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: vk_simple_bot
      POSTGRES_USER: vkuser
      POSTGRES_PASSWORD: secure_password_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vkuser -d vk_simple_bot"]
      interval: 10s
      timeout: 5s
      retries: 5

  vk-bot:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=vk_simple_bot
      - POSTGRES_USER=vkuser
      - POSTGRES_PASSWORD=secure_password_123
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  postgres_data:
